// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVF5K9IE8ThpJlT7Xyrl7llRHUk-JXEq0',
    appId: '1:11198046156:web:18291f13a1ae930b7e4769',
    messagingSenderId: '11198046156',
    projectId: 'hersphere-650dc',
    authDomain: 'hersphere-650dc.firebaseapp.com',
    storageBucket: 'hersphere-650dc.appspot.com',
    measurementId: 'G-S55LKNZBT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzwh9aIfkawLoA9r2dDKO7HTMVXff5ew',
    appId: '1:11198046156:android:d22b392bdb27a4317e4769',
    messagingSenderId: '11198046156',
    projectId: 'hersphere-650dc',
    storageBucket: 'hersphere-650dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2k6-2ijEgkpWjJWjkoN4e4z3tguzzRI',
    appId: '1:11198046156:ios:6f66894596373f027e4769',
    messagingSenderId: '11198046156',
    projectId: 'hersphere-650dc',
    storageBucket: 'hersphere-650dc.appspot.com',
    androidClientId: '11198046156-as9uu90jq4l095vi0vkuhdlk02kp7l7p.apps.googleusercontent.com',
    iosClientId: '11198046156-1jljukmpioi8a4raa00i6vr8o9skc95t.apps.googleusercontent.com',
    iosBundleId: 'com.example.hersphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2k6-2ijEgkpWjJWjkoN4e4z3tguzzRI',
    appId: '1:11198046156:ios:6f66894596373f027e4769',
    messagingSenderId: '11198046156',
    projectId: 'hersphere-650dc',
    storageBucket: 'hersphere-650dc.appspot.com',
    androidClientId: '11198046156-as9uu90jq4l095vi0vkuhdlk02kp7l7p.apps.googleusercontent.com',
    iosClientId: '11198046156-1jljukmpioi8a4raa00i6vr8o9skc95t.apps.googleusercontent.com',
    iosBundleId: 'com.example.hersphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVF5K9IE8ThpJlT7Xyrl7llRHUk-JXEq0',
    appId: '1:11198046156:web:b0b64e514d51aa177e4769',
    messagingSenderId: '11198046156',
    projectId: 'hersphere-650dc',
    authDomain: 'hersphere-650dc.firebaseapp.com',
    storageBucket: 'hersphere-650dc.appspot.com',
    measurementId: 'G-9YV2XJVS7J',
  );
}
